# fly.toml app configuration file generated for stack-overflow-clone-nameless-log-1050 on 2024-11-20T02:47:48Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stack-overflow-clone-nameless-log-1050'
primary_region = 'iad'
console_command = '/rails/bin/rails console'

[build]

[env]
  DATABASE_URL = 'sqlite3:///data/production.sqlite3'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
